instruction_memory:
	-iverilog -g2012 -o instruction_memory instruction_memory.sv instruction_memory_tb.sv

register_file_datapath:
	-iverilog -g2012 -o register_file_datapath register_file_datapath.sv register_file_datapath_tb.sv

